using FluentSourceGenerators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TUnit.Core; // Assuming TUnit

namespace FluentSourceGenerators.Tests;

// 1. Define the Model (Must be outside the Generator class or static)
public record HelloModel(string Name);

// 2. Define the Generator (Must implement IIncrementalGenerator)
[Generator]
public class SimpleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalGeneratorBuilder.Create()
            .StartSyntaxPipeline<HelloModel>()
            // Predicate
            .WithPredicate((node, _) => node is ClassDeclarationSyntax c && c.Identifier.Text.EndsWith("Greeter"))
            // Transform
            .WithTransform((ctx, ct) => new HelloModel(((ClassDeclarationSyntax)ctx.Node).Identifier.Text))
            // Output - FIX: Added 'ct' (CancellationToken) as the 3rd argument
            .WithOutput((spc, model, ct) =>
            {
                spc.AddSource($"{model.Name}.g.cs", $$"""
                                                      // <auto-generated/>
                                                      partial class {{model.Name}} {
                                                          public void SayHello() => System.Console.WriteLine("Hello from {{model.Name}}");
                                                      }
                                                      """);
            })
            .And()
            .Build() // FIX: Call Build() before Initialize()
            .Initialize(context);
    }
}

// 3. The Test Class
public class SimpleGeneratorTest
{
    [Test]
    public async Task Simple_GeneratesHelloMethod()
    {
        var input = "public partial class MyGreeter {}";

        // FIX: Passing 'SimpleGenerator', NOT 'SimpleGeneratorTest'
        var (diagnostics, output) = TestHelpers.RunGenerator<SimpleGenerator>(input);

        await Assert.That(diagnostics).IsEmpty();
        await Assert.That(output).Contains("Hello from MyGreeter");
    }
}
